// Generated by gencpp from file arm_lib/angle.msg
// DO NOT EDIT!


#ifndef ARM_LIB_MESSAGE_ANGLE_H
#define ARM_LIB_MESSAGE_ANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_lib
{
template <class ContainerAllocator>
struct angle_
{
  typedef angle_<ContainerAllocator> Type;

  angle_()
    : alpha(0.0)
    , beta(0.0)
    , gamma(0.0)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
    }
  angle_(const ContainerAllocator& _alloc)
    : alpha(0.0)
    , beta(0.0)
    , gamma(0.0)
    , dx(0.0)
    , dy(0.0)
    , dz(0.0)  {
  (void)_alloc;
    }



   typedef float _alpha_type;
  _alpha_type alpha;

   typedef float _beta_type;
  _beta_type beta;

   typedef float _gamma_type;
  _gamma_type gamma;

   typedef float _dx_type;
  _dx_type dx;

   typedef float _dy_type;
  _dy_type dy;

   typedef float _dz_type;
  _dz_type dz;





  typedef boost::shared_ptr< ::arm_lib::angle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_lib::angle_<ContainerAllocator> const> ConstPtr;

}; // struct angle_

typedef ::arm_lib::angle_<std::allocator<void> > angle;

typedef boost::shared_ptr< ::arm_lib::angle > anglePtr;
typedef boost::shared_ptr< ::arm_lib::angle const> angleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_lib::angle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_lib::angle_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arm_lib::angle_<ContainerAllocator1> & lhs, const ::arm_lib::angle_<ContainerAllocator2> & rhs)
{
  return lhs.alpha == rhs.alpha &&
    lhs.beta == rhs.beta &&
    lhs.gamma == rhs.gamma &&
    lhs.dx == rhs.dx &&
    lhs.dy == rhs.dy &&
    lhs.dz == rhs.dz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arm_lib::angle_<ContainerAllocator1> & lhs, const ::arm_lib::angle_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arm_lib

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::arm_lib::angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_lib::angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::angle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_lib::angle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::angle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_lib::angle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_lib::angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eaad8cd660da027597bb8c0321254020";
  }

  static const char* value(const ::arm_lib::angle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeaad8cd660da0275ULL;
  static const uint64_t static_value2 = 0x97bb8c0321254020ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_lib::angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_lib/angle";
  }

  static const char* value(const ::arm_lib::angle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_lib::angle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 alpha\n"
"float32 beta\n"
"float32 gamma\n"
"float32 dx\n"
"float32 dy\n"
"float32 dz\n"
;
  }

  static const char* value(const ::arm_lib::angle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_lib::angle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.alpha);
      stream.next(m.beta);
      stream.next(m.gamma);
      stream.next(m.dx);
      stream.next(m.dy);
      stream.next(m.dz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct angle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_lib::angle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_lib::angle_<ContainerAllocator>& v)
  {
    s << indent << "alpha: ";
    Printer<float>::stream(s, indent + "  ", v.alpha);
    s << indent << "beta: ";
    Printer<float>::stream(s, indent + "  ", v.beta);
    s << indent << "gamma: ";
    Printer<float>::stream(s, indent + "  ", v.gamma);
    s << indent << "dx: ";
    Printer<float>::stream(s, indent + "  ", v.dx);
    s << indent << "dy: ";
    Printer<float>::stream(s, indent + "  ", v.dy);
    s << indent << "dz: ";
    Printer<float>::stream(s, indent + "  ", v.dz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_LIB_MESSAGE_ANGLE_H
